language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
before_install:
  - pip install --user cpp-coveralls
script:
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 make coverage
after_success:
  - coveralls --exclude lib --exclude tests --gcov /usr/bin/gcov --gcov-options '\-lp'