name: aeon
version: 0.10.0.A
summary: "AEON: the private, secure, untraceable currency - http://www.aeon.cash"
description: |
    AEON is a private, secure, untraceable currency. You are your bank, you 
    control your funds, and nobody can trace your transfers.
grade: devel
confinement: strict

apps:
    aeond:
        daemon: forking
        command: |
          aeond-wrapper --detach --data-dir ${SNAP_COMMON} --config-file ${SNAP_USER_DATA}/etc/aeond.conf
        plugs:
            - network
            - network-bind
    aeon-wallet-rpc:
        command: |
          aeon-wallet-rpc --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network
            - network-bind
    aeon-wallet-cli:
        command: |
          aeon-wallet-cli --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network

parts:
    cmake-build:
        plugin: cmake
        configflags:
            - -DBDB_STATIC=1
            - -DUPNP_STATIC=1
            - -DBoost_USE_STATIC_LIBS=1
            - -DBoost_USE_STATIC_RUNTIME=1
            - -DARCH=default
        source: .
        build-packages:
            - gcc
            - pkg-config
            - libunbound-dev
            - libevent-dev
            - libboost-all-dev
            - libzmqpp-dev
            - libzmq3-dev
            - libsodium-dev
            - libdb-dev
            - libunwind-dev
            - libminiupnpc-dev
            - libldns-dev
            - libexpat1-dev
            - libreadline6-dev
            - bison
            - doxygen
            - graphviz
        stage-packages:
            - libminiupnpc10
            - libunbound2
            - libunwind8
        prime:
            - bin
            - usr/lib/
            - -usr/lib/gcc
            - -usr/share

    dist-files:
        plugin: dump
        source: .
        organize:
            contrib/snap/aeond.conf: etc/aeond.conf
            contrib/snap/aeond-wrapper: bin/aeond-wrapper
        prime:
            - etc
            - bin
